export interface Game {
    name: string;
    url: string;
    imageUrl: string;
}

export const games: Game[] = [
    { name: 'slope', url: 'https://classy-figolla-4956da.netlify.app/games/slope/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/slope.jpg' },
    { name: 'subway surfers', url: 'https://classy-figolla-4956da.netlify.app/games/subwaysurfers/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/subwaysurfers.jpeg' },
    { name: 'flappy bird', url: 'https://classy-figolla-4956da.netlify.app/games/flappy/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/flappybird.jpg' },
    { name: "papa's pizzaria", url: 'https://classy-figolla-4956da.netlify.app/games/papaspizzaria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papaspizzeria.jpg' },
    { name: "papa's burgeria", url: 'https://classy-figolla-4956da.netlify.app/games/papasburgeria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papasburgeria.jpg' },
    { name: 'super mario 64', url: 'https://classy-figolla-4956da.netlify.app/games/sm64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sm64.jpg' },
    { name: 'run 3', url: 'https://classy-figolla-4956da.netlify.app/games/run3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/run3.jpg' },
    { name: 'bitlife', url: 'https://classy-figolla-4956da.netlify.app/games/bitlife/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bitlife.jpg' },
    { name: 'crossy road', url: 'https://classy-figolla-4956da.netlify.app/games/crossy/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/crossyroad.jpg' },
    { name: 'minecraft [v1.5.2]', url: 'https://classy-figolla-4956da.netlify.app/games/mc/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mc.jpg' },
    { name: 'cookie clicker', url: 'https://classy-figolla-4956da.netlify.app/games/cookieclicker/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cookieclick.jpg' },
    { name: 'temple run 2', url: 'https://classy-figolla-4956da.netlify.app/games/templerun2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/templerun2.jpg' },
    { name: 'duck life 4', url: 'https://classy-figolla-4956da.netlify.app/games/ducklife4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ducklife4.jpg' },
    { name: 'chrome dino game', url: 'https://classy-figolla-4956da.netlify.app/games/dinogame/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/chromedino.jpg' },
    { name: 'jetpack joyride', url: 'https://classy-figolla-4956da.netlify.app/games/jetpackjoyride/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/jetpackjoyride.jpg' },
    { name: 'retro bowl', url: 'https://classy-figolla-4956da.netlify.app/games/retrobowl/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/retrobowl.jpg' },
    { name: 'fruit ninja', url: 'https://classy-figolla-4956da.netlify.app/games/fruitninja/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fruitninja.jpg' },
    { name: 'doodle jump', url: 'https://classy-figolla-4956da.netlify.app/games/doodlejump/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/doodlejump.jpg' },
    { name: '2048', url: 'https://classy-figolla-4956da.netlify.app/games/2048/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/2048.jpg' },
    { name: 'tetris', url: 'https://classy-figolla-4956da.netlify.app/games/tetris/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/tetris.jpg' },
    { name: 'fancy pants adventure', url: 'https://classy-figolla-4956da.netlify.app/games/fancypantsadventure/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fancypantsadventure.jpg' },
    { name: 'happy wheels', url: 'https://classy-figolla-4956da.netlify.app/games/happywheels/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/happywheels.jpg' },
    { name: "papa's hotdoggeria", url: 'https://classy-figolla-4956da.netlify.app/games/papashotdoggeria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papashotdoggeria.jpg' },
    { name: 'paperio2', url: 'https://classy-figolla-4956da.netlify.app/games/paperio2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/paperio2.jpg' },
    { name: 'super hot', url: 'https://classy-figolla-4956da.netlify.app/games/superhot/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/superhot.jpg' },
    { name: 'the binding of isaac', url: 'https://classy-figolla-4956da.netlify.app/games/thebindingofisaac/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/thebindingofisaac.jpg' },
    { name: 'townscaper', url: 'https://classy-figolla-4956da.netlify.app/games/townscaper/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/townscaper.jpg' },
    { name: 'tunnel rush', url: 'https://classy-figolla-4956da.netlify.app/games/tunnelrush/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/tunnelrush.jpg' },
    { name: 'theme hotel', url: 'https://classy-figolla-4956da.netlify.app/games/themehotel/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/themehotel.jpg' },
    { name: 'escaping the prison', url: 'https://classy-figolla-4956da.netlify.app/games/escapingtheprison/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/escapingtheprison.jpg' },
    { name: 'stealing the diamond', url: 'https://classy-figolla-4956da.netlify.app/games/stealingthediamond/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stealingthediamond.jpg' },
    { name: 'infiltrating the airship', url: 'https://classy-figolla-4956da.netlify.app/games/infiltratingtheairship/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/infiltratingtheairship.jpg' },
    { name: 'fleeing the complex', url: 'https://classy-figolla-4956da.netlify.app/games/fleeingthecomplex/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fleeingthecomplex.jpg' },
    { name: 'the impossible quiz', url: 'https://classy-figolla-4956da.netlify.app/games/theimpossiblequiz/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/theimpossiblequiz.jpg' },
    { name: 'solitaire', url: 'https://classy-figolla-4956da.netlify.app/games/solitaire/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/solitaire.jpg' },
    { name: 'drift hunters', url: 'https://classy-figolla-4956da.netlify.app/games/drifthunters/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/drifthunters.jpg' },
    { name: 'vex 6', url: 'https://classy-figolla-4956da.netlify.app/games/vex6/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/vex6.jpg' },
    { name: 'among us fangame', url: 'https://classy-figolla-4956da.netlify.app/games/amongus/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/amongus.jpg' },
    { name: 'edge surf', url: 'https://classy-figolla-4956da.netlify.app/games/surf/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/surf.jpg' },
    { name: 'motox3m', url: 'https://classy-figolla-4956da.netlify.app/games/motox3m/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/motox3m.jpeg' },
    { name: 'fnaf 1', url: 'https://classy-figolla-4956da.netlify.app/games/fnaf/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fnaf.jpg' },
    { name: 'fnaf 2', url: 'https://classy-figolla-4956da.netlify.app/games/fnaf-2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fnaf2.jpg' },
    { name: 'fnaf 3', url: 'https://classy-figolla-4956da.netlify.app/games/fnaf-3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fnaf3.jpg' },
    { name: 'fnaf 4', url: 'https://classy-figolla-4956da.netlify.app/games/fnaf-4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fnaf4.jpg' },
    { name: 'riddle school', url: 'https://classy-figolla-4956da.netlify.app/games/riddleschool/riddleschool1/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/riddleschool.jpg' },
    { name: 'riddle school 2', url: 'https://classy-figolla-4956da.netlify.app/games/riddleschool/riddleschool2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/riddleschool2.jpg' },
    { name: 'riddle school 3', url: 'https://classy-figolla-4956da.netlify.app/games/riddleschool/riddleschool3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/riddleschool3.jpg' },
    { name: 'riddle school 4', url: 'https://classy-figolla-4956da.netlify.app/games/riddleschool/riddleschool4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/riddleschool4.jpg' },
    { name: 'riddle school 5', url: 'https://classy-figolla-4956da.netlify.app/games/riddleschool/riddleschool5/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/riddleschool5.jpg' },
    { name: 'riddle transfer', url: 'https://classy-figolla-4956da.netlify.app/games/riddleschool/riddletransfer/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/riddletransfer.jpg' },
    { name: 'riddle transfer 2', url: 'https://classy-figolla-4956da.netlify.app/games/riddleschool/riddletransfer2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/riddletransfer2.jpg' },
    { name: 'drift boss', url: 'https://classy-figolla-4956da.netlify.app/games/driftboss/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/driftboss.jpg' },
    { name: 'friday night funkin', url: 'https://classy-figolla-4956da.netlify.app/games/fnf/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fnf.jpg' },
    { name: 'pacman', url: 'https://classy-figolla-4956da.netlify.app/games/pacman/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pacman.jpg' },
    { name: "papa's pancakeria", url: 'https://classy-figolla-4956da.netlify.app/games/papaspancakeria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papaspancakeria.jpg' },
    { name: 'rooftop snipers', url: 'https://classy-figolla-4956da.netlify.app/games/rooftop/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/rooftopsnipers.jpg' },
    { name: "baldi's basics", url: 'https://classy-figolla-4956da.netlify.app/games/baldisbasics/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/baldisbasics.jpg' },
    { name: 'bob the robber 2', url: 'https://classy-figolla-4956da.netlify.app/games/bobtherobber2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bobtherobber2.jpg' },
    { name: 'minesweeper', url: 'https://classy-figolla-4956da.netlify.app/games/minesweeper/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/minesweeper.jpg' },
    { name: 'pokemon emerald', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonemerald/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonemerald.jpg' },
    { name: 'pokemon fire red', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonfirered/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonfirered.jpg' },
    { name: 'super mario bros', url: 'https://classy-figolla-4956da.netlify.app/games/supermariobros/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermariobros.jpg' },
    { name: 'super mario kart', url: 'https://classy-figolla-4956da.netlify.app/games/supermariokart/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermariokart.jpg' },
    { name: 'super mario world', url: 'https://classy-figolla-4956da.netlify.app/games/supermarioworld/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermarioworld.jpg' },
    { name: 'there is no game', url: 'https://classy-figolla-4956da.netlify.app/games/thereisnogame/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/thereisnogame.jpg' },
    { name: "world's hardest game", url: 'https://classy-figolla-4956da.netlify.app/games/worldshardestgame/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/worldshardestgame.jpg' },
    { name: 'castlevania', url: 'https://classy-figolla-4956da.netlify.app/games/castlevania/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/castlevania.jpg' },
    { name: 'donkey kong', url: 'https://classy-figolla-4956da.netlify.app/games/donkeykong/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/donkeykong.jpg' },
    { name: 'dr mario', url: 'https://classy-figolla-4956da.netlify.app/games/drmario/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/drmario.jpg' },
    { name: 'metroid', url: 'https://classy-figolla-4956da.netlify.app/games/metroid/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/metroid.jpg' },
    { name: 'super mario bros 2', url: 'https://classy-figolla-4956da.netlify.app/games/supermariobros2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermariobros2.jpg' },
    { name: 'super mario bros 3', url: 'https://classy-figolla-4956da.netlify.app/games/supermariobros3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermariobros3.jpg' },
    { name: 'the legend of zelda', url: 'https://classy-figolla-4956da.netlify.app/games/thelegendofzelda/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/thelegendofzelda.jpg' },
    { name: 'warioware', url: 'https://classy-figolla-4956da.netlify.app/games/warioware/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/warioware.jpg' },
    { name: "yoshi's island", url: 'https://classy-figolla-4956da.netlify.app/games/yoshisisland/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/yoshisisland.jpg' },
    { name: 'donkey kong land', url: 'https://classy-figolla-4956da.netlify.app/games/donkeykongland/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/donkeykongland.jpg' },
    { name: "kirby's dream land", url: 'https://classy-figolla-4956da.netlify.app/games/kirbysdreamland/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/kirbysdreamland.jpg' },
    { name: 'super mario land', url: 'https://classy-figolla-4956da.netlify.app/games/supermarioland/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermarioland.jpg' },
    { name: 'doge miner', url: 'https://classy-figolla-4956da.netlify.app/games/dogeminer/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/dogeminer.jpg' },
    { name: 'tanuki sunset', url: 'https://classy-figolla-4956da.netlify.app/games/tanukisunset/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/tanukisunset.jpg' },
    { name: 'aquapark slides', url: 'https://classy-figolla-4956da.netlify.app/games/aquaparkslides/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/aquaparkslides.jpg' },
    { name: 'color switch', url: 'https://classy-figolla-4956da.netlify.app/games/colorswitch/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/colorswitch.jpg' },
    { name: "papa's freezeria", url: 'https://classy-figolla-4956da.netlify.app/games/papasfreezeria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papasfreezeria.jpg' },
    { name: 'btd', url: 'https://classy-figolla-4956da.netlify.app/games/btd/btd/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/btd.jpg' },
    { name: 'btd 2', url: 'https://classy-figolla-4956da.netlify.app/games/btd/btd2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/btd2.jpg' },
    { name: 'btd 3', url: 'https://classy-figolla-4956da.netlify.app/games/btd/btd3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/btd3.jpg' },
    { name: 'btd 4', url: 'https://classy-figolla-4956da.netlify.app/games/btd/btd4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/btd4.jpg' },
    { name: 'bomberman', url: 'https://classy-figolla-4956da.netlify.app/games/bomberman/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bomberman.jpg' },
    { name: 'fire emblem', url: 'https://classy-figolla-4956da.netlify.app/games/fireemblem/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fireemblem.jpg' },
    { name: 'ice climber', url: 'https://classy-figolla-4956da.netlify.app/games/iceclimber/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/iceclimber.jpg' },
    { name: 'mario kart super circuit', url: 'https://classy-figolla-4956da.netlify.app/games/mariokartsupercircuit/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariokartsupercircuit.jpg' },
    { name: 'pokemon leaf green', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonleafgreen/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonleafgreen.jpg' },
    { name: 'pokemon ruby', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonruby/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonruby.jpg' },
    { name: 'pokemon sapphire', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonsapphire/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonsapphire.jpg' },
    { name: 'superstar saga', url: 'https://classy-figolla-4956da.netlify.app/games/superstarsaga/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/superstarsaga.jpg' },
    { name: 'adofai', url: 'https://classy-figolla-4956da.netlify.app/games/adofai/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/adofai.jpg' },
    { name: 'super smash flash', url: 'https://classy-figolla-4956da.netlify.app/games/supersmashflash/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supersmashflash.jpg' },
    { name: 'super meat boy', url: 'https://classy-figolla-4956da.netlify.app/games/supermeatboy/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermeatboy.jpg' },
    { name: 'stickman hook', url: 'https://classy-figolla-4956da.netlify.app/games/stickmanhook/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stickmanhook.jpg' },
    { name: 'defend the tank', url: 'https://classy-figolla-4956da.netlify.app/games/defendthetank/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/defendthetank.jpg' },
    { name: 'sort the court', url: 'https://classy-figolla-4956da.netlify.app/games/sortthecourt/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sortthecourt.jpg' },
    { name: 'this is the only level', url: 'https://classy-figolla-4956da.netlify.app/games/thisistheonlylevel/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/thisistheonlylevel.jpg' },
    { name: 'run', url: 'https://classy-figolla-4956da.netlify.app/games/run/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/run.jpg' },
    { name: 'run 2', url: 'https://classy-figolla-4956da.netlify.app/games/run2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/run2.jpg' },
    { name: 'battleships', url: 'https://classy-figolla-4956da.netlify.app/games/battleships/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/battleships.jpg' },
    { name: 'breaking the bank', url: 'https://classy-figolla-4956da.netlify.app/games/breakingthebank/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/breakingthebank.jpg' },
    { name: 'duck life', url: 'https://classy-figolla-4956da.netlify.app/games/ducklife/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ducklife.jpg' },
    { name: 'duck life 2', url: 'https://classy-figolla-4956da.netlify.app/games/ducklife2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ducklife2.jpg' },
    { name: 'duck life 3', url: 'https://classy-figolla-4956da.netlify.app/games/ducklife3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ducklife3.jpg' },
    { name: 'line rider', url: 'https://classy-figolla-4956da.netlify.app/games/linerider/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/linerider.jpg' },
    { name: 'mario combat', url: 'https://classy-figolla-4956da.netlify.app/games/mariocombat/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariocombat.jpg' },
    { name: 'raft wars 2', url: 'https://classy-figolla-4956da.netlify.app/games/raftwars2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/raftwars2.jpg' },
    { name: 'space invaders', url: 'https://classy-figolla-4956da.netlify.app/games/spaceinvaders/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/spaceinvaders.jpg' },
    { name: 'animal crossing', url: 'https://classy-figolla-4956da.netlify.app/games/animalcrossingwildworld/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/animalcrossingwildworld.jpg' },
    { name: 'mario kart ds', url: 'https://classy-figolla-4956da.netlify.app/games/mariokartds/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariokartds.jpg' },
    { name: 'new super mario bros', url: 'https://classy-figolla-4956da.netlify.app/games/newsupermariobros/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/newsupermariobros.jpg' },
    { name: 'nintendogs', url: 'https://classy-figolla-4956da.netlify.app/games/nintendogs/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/nintendogs.jpg' },
    { name: 'super mario 64 ds', url: 'https://classy-figolla-4956da.netlify.app/games/sm64ds/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sm64ds.jpg' },
    { name: 'gun mayhem', url: 'https://classy-figolla-4956da.netlify.app/games/gunmayhem/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/gunmayhem.jpg' },
    { name: 'learn to fly', url: 'https://classy-figolla-4956da.netlify.app/games/learntofly/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/learntofly.jpg' },
    { name: 'rooftop snipers 2', url: 'https://classy-figolla-4956da.netlify.app/games/rooftop2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/rooftopsnipers2.jpg' },
    { name: 'fireboy and watergirl', url: 'https://classy-figolla-4956da.netlify.app/games/fireboywatergirl/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fireboyandwatergirl.jpg' },
    { name: 'chibi knight', url: 'https://classy-figolla-4956da.netlify.app/games/chibiknight/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/chibiknight.jpg' },
    { name: 'cluster rush', url: 'https://classy-figolla-4956da.netlify.app/games/clusterrush/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/clusterrush.jpg' },
    { name: 'doodle defender', url: 'https://classy-figolla-4956da.netlify.app/games/doodledefender/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/doodledefender.jpg' },
    { name: 'learn to fly 2', url: 'https://classy-figolla-4956da.netlify.app/games/learntofly2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/learntofly2.jpg' },
    { name: "papa's scooperia", url: 'https://classy-figolla-4956da.netlify.app/games/papasscooperia/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papasscooperia.jpg' },
    { name: "papa's sushiria", url: 'https://classy-figolla-4956da.netlify.app/games/papassushiria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papassushiria.jpg' },
    { name: "papa's wingeria", url: 'https://classy-figolla-4956da.netlify.app/games/papaswingeria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papassushiria.jpg' },
    { name: 'raft wars', url: 'https://classy-figolla-4956da.netlify.app/games/raftwars/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/raftwars.jpg' },
    { name: 'unfair mario', url: 'https://classy-figolla-4956da.netlify.app/games/unfairmario/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/unfairmario.jpg' },
    { name: 'boxing physics 2', url: 'https://classy-figolla-4956da.netlify.app/games/boxingphysics2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/boxingphysics2.jpg' },
    { name: 'ace attorney', url: 'https://classy-figolla-4956da.netlify.app/games/aceattorney/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/aceattorney.jpg' },
    { name: 'metal gear solid', url: 'https://classy-figolla-4956da.netlify.app/games/metalgearsolid/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/metalgearsolid.jpg' },
    { name: 'mother 3', url: 'https://classy-figolla-4956da.netlify.app/games/mother3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mother3.jpg' },
    { name: 'pokemon diamond', url: 'https://classy-figolla-4956da.netlify.app/games/pokemondiamond/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemondiamond.jpg' },
    { name: 'pokemon platinum', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonplatinum/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonplatinum.jpg' },
    { name: 'pokemon soulsilver', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonsoulsilver/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonsoulsilver.jpg' },
    { name: 'advance wars', url: 'https://classy-figolla-4956da.netlify.app/games/advancewars/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/advancewars.jpg' },
    { name: 'banjo pilot', url: 'https://classy-figolla-4956da.netlify.app/games/banjopilot/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/banjopilot.jpg' },
    { name: 'super monkey ball jr', url: 'https://classy-figolla-4956da.netlify.app/games/supermonkeyballjr/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermonkeyballjr.jpg' },
    { name: 'the impossible quiz 2', url: 'https://classy-figolla-4956da.netlify.app/games/theimpossiblequiz2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/theimpossiblequiz2.jpg' },
    { name: "papa's donuteria", url: 'https://classy-figolla-4956da.netlify.app/games/papasdonuteria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papasdonuteria.jpg' },
    { name: 'fancy pants adventure 2', url: 'https://classy-figolla-4956da.netlify.app/games/fancypantsadventure2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fancypantsadventure2.jpg' },
    { name: 'tiny fishing', url: 'https://classy-figolla-4956da.netlify.app/games/tinyfishing/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/tinyfishing.jpg' },
    { name: 'big red button', url: 'https://classy-figolla-4956da.netlify.app/games/bigredbutton/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bigredbutton.jpg' },
    { name: 'achievement unlocked', url: 'https://classy-figolla-4956da.netlify.app/games/achievementunlocked/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/achievementunlocked.jpg' },
    { name: 'kirby mass attack', url: 'https://classy-figolla-4956da.netlify.app/games/kirbymassattack/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/kirbymassattack.jpg' },
    { name: 'sonic advance', url: 'https://classy-figolla-4956da.netlify.app/games/sonicadvance/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sonicadvance.jpg' },
    { name: 'worms world party', url: 'https://classy-figolla-4956da.netlify.app/games/wormsworldparty/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/wormsworldparty.jpg' },
    { name: 'bad ice cream', url: 'https://classy-figolla-4956da.netlify.app/games/badicecream/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/badicecream.jpg' },
    { name: 'bad ice cream 2', url: 'https://classy-figolla-4956da.netlify.app/games/badicecream2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/badicecream2.jpg' },
    { name: 'bad ice cream 3', url: 'https://classy-figolla-4956da.netlify.app/games/badicecream3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/badicecream3.jpg' },
    { name: 'adventure captialist', url: 'https://classy-figolla-4956da.netlify.app/games/adventurecapitalist/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/adventurecaptialist.jpg' },
    { name: 'monkey mart', url: 'https://classy-figolla-4956da.netlify.app/games/monkeymart/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/monkeymart.jpg' },
    { name: 'doom 64', url: 'https://classy-figolla-4956da.netlify.app/games/doom64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/doom64.jpg' },
    { name: 'banjo kazooie', url: 'https://classy-figolla-4956da.netlify.app/games/banjokazooie/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/banjokazooie.jpg' },
    { name: 'donkey kong 64', url: 'https://classy-figolla-4956da.netlify.app/games/donkeykong64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/donkeykong64.jpg' },
    { name: 'f-zero x', url: 'https://classy-figolla-4956da.netlify.app/games/fzerox/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fzerox.jpg' },
    { name: 'kirby 64', url: 'https://classy-figolla-4956da.netlify.app/games/kirby64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/kirby64.jpg' },
    { name: 'mario kart 64', url: 'https://classy-figolla-4956da.netlify.app/games/mariokart64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariokart64.jpg' },
    { name: 'mario party', url: 'https://classy-figolla-4956da.netlify.app/games/marioparty/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/marioparty.jpg' },
    { name: 'mario party 2', url: 'https://classy-figolla-4956da.netlify.app/games/marioparty2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/marioparty2.jpg' },
    { name: 'ocarina of time', url: 'https://classy-figolla-4956da.netlify.app/games/ocarinaoftime/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ocarinaoftime.jpg' },
    { name: 'star fox 64', url: 'https://classy-figolla-4956da.netlify.app/games/starfox64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/starfox64.jpg' },
    { name: 'super smash bros', url: 'https://classy-figolla-4956da.netlify.app/games/supersmashbros/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supersmashbros.jpg' },
    { name: 'street fighter 2', url: 'https://classy-figolla-4956da.netlify.app/games/streetfighter2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/streetfighter2.jpg' },
    { name: 'getaway shootout', url: 'https://classy-figolla-4956da.netlify.app/games/getawayshootout/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/getawayshootout.jpg' },
    { name: 'rabbit samurai', url: 'https://classy-figolla-4956da.netlify.app/games/rabbitsamurai/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/rabbitsamurai.jpg' },
    { name: 'mario party ds', url: 'https://classy-figolla-4956da.netlify.app/games/mariopartyds/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariopartyds.jpg' },
    { name: 'professor layton', url: 'https://classy-figolla-4956da.netlify.app/games/professorlayton/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/professorlayton.jpg' },
    { name: 'scribblenauts', url: 'https://classy-figolla-4956da.netlify.app/games/scribblenauts/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/scribblenauts.jpg' },
    { name: 'advance wars 2', url: 'https://classy-figolla-4956da.netlify.app/games/advancewars2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/advancewars2.jpg' },
    { name: 'harvest moon', url: 'https://classy-figolla-4956da.netlify.app/games/harvestmoon/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/harvestmoon.jpg' },
    { name: 'mario tennis', url: 'https://classy-figolla-4956da.netlify.app/games/mariotennis/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariotennis.jpg' },
    { name: 'mega man zero', url: 'https://classy-figolla-4956da.netlify.app/games/megamanzero/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/megamanzero.jpg' },
    { name: 'mystery dungeon', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonmysterydungeon/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonmysterydungeon.jpg' },
    { name: 'pokemon unbound', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonunbound/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonunbound.jpg' },
    { name: "papa's cheeseria", url: 'https://classy-figolla-4956da.netlify.app/games/papascheeseria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papascheeseria.jpg' },
    { name: "papa's cupcakeria", url: 'https://classy-figolla-4956da.netlify.app/games/papascupcakeria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papascupcakeria.jpg' },
    { name: "papa's bakeria", url: 'https://classy-figolla-4956da.netlify.app/games/papasbakeria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papasbakeria.jpg' },
    { name: "papa's pastaria", url: 'https://classy-figolla-4956da.netlify.app/games/papaspastaria/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papaspastaria.jpg' },
    { name: 'gun mayhem 2', url: 'https://classy-figolla-4956da.netlify.app/games/gunmayhem2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/gunmayhem2.jpg' },
    { name: 'gun mayhem redux', url: 'https://classy-figolla-4956da.netlify.app/games/gunmayhemredux/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/gunmayhemredux.jpg' },
    { name: 'achievement unlocked 2', url: 'https://classy-figolla-4956da.netlify.app/games/achievementunlocked2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/achievementunlocked2.jpg' },
    { name: 'achievement unlocked 3', url: 'https://classy-figolla-4956da.netlify.app/games/achievementunlocked3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/achievementunlocked3.jpg' },
    { name: 'factory balls', url: 'https://classy-figolla-4956da.netlify.app/games/factoryballs/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/factoryballs.jpg' },
    { name: 'skywire', url: 'https://classy-figolla-4956da.netlify.app/games/skywire/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/skywire.jpg' },
    { name: 'super mario flash', url: 'https://classy-figolla-4956da.netlify.app/games/supermarioflash/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermarioflash.jpg' },
    { name: 'golden sun', url: 'https://classy-figolla-4956da.netlify.app/games/goldensun/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/goldensun.jpg' },
    { name: 'metroid fusion', url: 'https://classy-figolla-4956da.netlify.app/games/metroidfusion/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/metroidfusion.jpg' },
    { name: 'dbz: supersonic warriors', url: 'https://classy-figolla-4956da.netlify.app/games/dbzsupersonicwarriors/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/goldensun.jpg' },
    { name: 'wario land 4', url: 'https://classy-figolla-4956da.netlify.app/games/warioland4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/warioland4.jpg' },
    { name: 'duck life 5', url: 'https://classy-figolla-4956da.netlify.app/games/ducklife5/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ducklife5.jpg' },
    { name: 'learn to fly 3', url: 'https://classy-figolla-4956da.netlify.app/games/learntofly3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/learntofly3.jpg' },
    { name: 'bloxors', url: 'https://classy-figolla-4956da.netlify.app/games/bloxors/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bloxors.jpg' },
    { name: 'electric man 2', url: 'https://classy-figolla-4956da.netlify.app/games/electricman2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/electricman2.jpg' },
    { name: 'portal', url: 'https://classy-figolla-4956da.netlify.app/games/portal/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/portal.jpg' },
    { name: 'portal 2', url: 'https://classy-figolla-4956da.netlify.app/games/portal2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/portal2.jpg' },
    { name: 'skywire 2', url: 'https://classy-figolla-4956da.netlify.app/games/skywire2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/skywire2.jpg' },
    { name: 'duck life 6', url: 'https://classy-figolla-4956da.netlify.app/games/ducklife6/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ducklife6.jpg' },
    { name: 'boxing random', url: 'https://classy-figolla-4956da.netlify.app/games/boxingrandom/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/boxingrandom.jpg' },
    { name: 'cell machine', url: 'https://classy-figolla-4956da.netlify.app/games/cellmachine/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cellmachine.jpg' },
    { name: 'stickman boost', url: 'https://classy-figolla-4956da.netlify.app/games/stickmanboost/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stickmanboost.jpg' },
    { name: 'vex 3', url: 'https://classy-figolla-4956da.netlify.app/games/vex3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/vex3.jpg' },
    { name: 'vex 4', url: 'https://classy-figolla-4956da.netlify.app/games/vex4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/vex4.jpg' },
    { name: 'skibidi toilet 1v100', url: 'https://classy-figolla-4956da.netlify.app/games/skibidi1v100/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/skibiditoilet1v100.jpg' },
    { name: 'golden eye 007', url: 'https://classy-figolla-4956da.netlify.app/games/goldeneye007/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/goldeneye007.jpg' },
    { name: "majora's mask", url: 'https://classy-figolla-4956da.netlify.app/games/majorasmask/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/majorasmask.jpg' },
    { name: 'paper mario', url: 'https://classy-figolla-4956da.netlify.app/games/papermario/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papermario.jpg' },
    { name: 'mario golf', url: 'https://classy-figolla-4956da.netlify.app/games/mariogolf/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariogolf.jpg' },
    { name: 'pokemon stadium', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonstadium/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonstadium.jpg' },
    { name: 'excitebike 64', url: 'https://classy-figolla-4956da.netlify.app/games/excitebike64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/excitebike64.jpg' },
    { name: 'pokemon snap', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonsnap/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonsnap.jpg' },
    { name: 'mario party 3', url: 'https://classy-figolla-4956da.netlify.app/games/marioparty3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/marioparty3.jpg' },
    { name: 'sonic advance 2', url: 'https://classy-figolla-4956da.netlify.app/games/sonicadvance2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sonicadvance2.jpg' },
    { name: 'bowsers inside story', url: 'https://classy-figolla-4956da.netlify.app/games/bowsersinsidestory/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bowsersinsidestory.jpg' },
    { name: 'spirit tracks', url: 'https://classy-figolla-4956da.netlify.app/games/spirittracks/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/spirittracks.jpg' },
    { name: 'the sims 2', url: 'https://classy-figolla-4956da.netlify.app/games/thesims2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/thesims2.jpg' },
    { name: 'tetris ds', url: 'https://classy-figolla-4956da.netlify.app/games/tetrisds/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/tetrisds.jpg' },
    { name: 'sonic rush', url: 'https://classy-figolla-4956da.netlify.app/games/sonicrush/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sonicrush.jpg' },
    { name: 'the sims 3', url: 'https://classy-figolla-4956da.netlify.app/games/thesims3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/thesims3.jpg' },
    { name: 'super princess peach', url: 'https://classy-figolla-4956da.netlify.app/games/superprincesspeach/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/superprincesspeach.jpg' },
    { name: 'lego batman', url: 'https://classy-figolla-4956da.netlify.app/games/legobatman/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/legobatman.jpg' },
    { name: 'doom 2', url: 'https://classy-figolla-4956da.netlify.app/games/doom2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/doomii.jpg' },
    { name: 'duke nukem advance', url: 'https://classy-figolla-4956da.netlify.app/games/dukenukemadvance/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/dukenukemadvance.jpg' },
    { name: 'mario party advance', url: 'https://classy-figolla-4956da.netlify.app/games/mariopartyadvance/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariopartyadvance.jpg' },
    { name: 'mario pinball land', url: 'https://classy-figolla-4956da.netlify.app/games/mariopinballland/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariopinballland.jpg' },
    { name: 'pacman world', url: 'https://classy-figolla-4956da.netlify.app/games/pacmanworld/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pacmanworld.jpg' },
    { name: 'rayman 3', url: 'https://classy-figolla-4956da.netlify.app/games/rayman3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/rayman3.jpg' },
    { name: 'shrek 2', url: 'https://classy-figolla-4956da.netlify.app/games/shrek2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shrek2.jpg' },
    { name: 'simcity 2000', url: 'https://classy-figolla-4956da.netlify.app/games/simcity/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/simcity2000.jpg' },
    { name: 'simpsons road rage', url: 'https://classy-figolla-4956da.netlify.app/games/simpsonsroadrage/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/simpsonsroadrage.jpg' },
    { name: 'diddy kong racing', url: 'https://classy-figolla-4956da.netlify.app/games/diddykongracing/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/diddykongracing.jpg' },
    { name: 'wave race 64', url: 'https://classy-figolla-4956da.netlify.app/games/waverace64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/waveracing.jpg' },
    { name: 'quest 64', url: 'https://classy-figolla-4956da.netlify.app/games/quest64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/quest64.jpg' },
    { name: 'gex 64', url: 'https://classy-figolla-4956da.netlify.app/games/gex64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/gex64.jpg' },
    { name: 'duke nukem 64', url: 'https://classy-figolla-4956da.netlify.app/games/dukenukem64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/dukenukem64.jpg' },
    { name: 'mortal kombat 4', url: 'https://classy-figolla-4956da.netlify.app/games/mortalkombat4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mortalkombat4.jpg' },
    { name: 'bad piggies', url: 'https://classy-figolla-4956da.netlify.app/games/badpiggies/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/badpiggies.jpg' },
    { name: 'super mario flash 2', url: 'https://classy-figolla-4956da.netlify.app/games/supermarioflash2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermarioflash2.jpg' },
    { name: 'swords and sandals', url: 'https://classy-figolla-4956da.netlify.app/games/swordsandsandals/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/swordsandsandals.jpg' },
    { name: 'swords and sandals 2', url: 'https://classy-figolla-4956da.netlify.app/games/swordsandsandals2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/swordsandsandals2.jpg' },
    { name: 'wordle', url: 'https://classy-figolla-4956da.netlify.app/games/wordle/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/wordle.jpg' },
    { name: 'vex', url: 'https://classy-figolla-4956da.netlify.app/games/vex/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/vex.jpg' },
    { name: 'vex 2', url: 'https://classy-figolla-4956da.netlify.app/games/vex2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/vex2.jpg' },
    { name: 'vex 5', url: 'https://classy-figolla-4956da.netlify.app/games/vex5/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/vex5.jpg' },
    { name: 'vex 7', url: 'https://classy-figolla-4956da.netlify.app/games/vex7/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/vex7.jpg' },
    { name: 'stack', url: 'https://classy-figolla-4956da.netlify.app/games/stack/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stack.jpg' },
    { name: 'skibidi toilet attack', url: 'https://classy-figolla-4956da.netlify.app/games/skibiditoiletattack/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/skibiditoiletattack.jpg' },
    { name: 'motox3m pool', url: 'https://classy-figolla-4956da.netlify.app/games/motox3mpool/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/motox3mpool.jpg' },
    { name: 'offline paradise', url: 'https://classy-figolla-4956da.netlify.app/games/offlineparadise/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/offlineparadise.jpg' },
    { name: 'link to the past', url: 'https://classy-figolla-4956da.netlify.app/games/linktothepast/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/linktothepast.jpg' },
    { name: 'donkey kong country', url: 'https://classy-figolla-4956da.netlify.app/games/donkeykongcountry/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/donkeykongcountry.jpg' },
    { name: 'donkey kong country 2', url: 'https://classy-figolla-4956da.netlify.app/games/donkeykongcountry2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/donkeykongcountry2.jpg' },
    { name: 'super bomberman', url: 'https://classy-figolla-4956da.netlify.app/games/superbomberman/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/superbomberman.jpg' },
    { name: 'mario paint', url: 'https://classy-figolla-4956da.netlify.app/games/mariopaint/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mariopaint.jpg' },
    { name: 'mega man x', url: 'https://classy-figolla-4956da.netlify.app/games/megamanx/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/megamanx.jpg' },
    { name: 'super mario rpg', url: 'https://classy-figolla-4956da.netlify.app/games/supermariorpg/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermariorpg.jpg' },
    { name: 'super tennis', url: 'https://classy-figolla-4956da.netlify.app/games/supertennis/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supertennis.jpg' },
    { name: "wario's woods", url: 'https://classy-figolla-4956da.netlify.app/games/warioswoods/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/warioswoods.jpg' },
    { name: 'worlds hardest game 2', url: 'https://classy-figolla-4956da.netlify.app/games/worldshardestgame2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/worldshardestgame2.jpg' },
    { name: 'bubble tanks 2', url: 'https://classy-figolla-4956da.netlify.app/games/bubbletanks2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bubbletanks2.jpg' },
    { name: 'choose your weapon', url: 'https://classy-figolla-4956da.netlify.app/games/chooseyourweapon/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/chooseyourweapon.jpg' },
    { name: 'choose your weapon 2', url: 'https://classy-figolla-4956da.netlify.app/games/chooseyourweapon2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/chooseyourweapon2.jpg' },
    { name: 'choose your weapon 3', url: 'https://classy-figolla-4956da.netlify.app/games/chooseyourweapon3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/chooseyourweapon3.jpg' },
    { name: 'connect 4', url: 'https://classy-figolla-4956da.netlify.app/games/connect4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/connect4.jpg' },
    { name: 'electric box', url: 'https://classy-figolla-4956da.netlify.app/games/electricbox/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/electricbox.jpg' },
    { name: 'mc tower defence 2', url: 'https://classy-figolla-4956da.netlify.app/games/mctowerdefence2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mctowerdefence2.jpg' },
    { name: 'cars 2', url: 'https://classy-figolla-4956da.netlify.app/games/cars2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cars2.jpg' },
    { name: 'cooking mama', url: 'https://classy-figolla-4956da.netlify.app/games/cookingmama/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cookingmama.jpg' },
    { name: 'adventure time', url: 'https://classy-figolla-4956da.netlify.app/games/adventuretime/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/adventuretimeheyiceking.jpg' },
    { name: 'garfield gets real', url: 'https://classy-figolla-4956da.netlify.app/games/garfieldgetsreal/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/garfieldgetsreal.jpg' },
    { name: 'warioware touched', url: 'https://classy-figolla-4956da.netlify.app/games/wariowaretouched/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/wariowaretouched.jpg' },
    { name: 'kirby power paintbrush', url: 'https://classy-figolla-4956da.netlify.app/games/kirbypowerpaintbrush/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/kirbypowerpaintbrush.jpg' },
    { name: 'sonic and knuckles', url: 'https://classy-figolla-4956da.netlify.app/games/sonicandknuckles/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sonicandknuckles.jpg' },
    { name: 'altered beast', url: 'https://classy-figolla-4956da.netlify.app/games/alteredbeast/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/alteredbeast.jpg' },
    { name: 'sonic spinball', url: 'https://classy-figolla-4956da.netlify.app/games/sonicspinball/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sonicspinball.jpg' },
    { name: 'sonic the hedgehog 3', url: 'https://classy-figolla-4956da.netlify.app/games/sonicthehedgehog3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sonicthehedgehog3.jpg' },
    { name: 'streets of rage', url: 'https://classy-figolla-4956da.netlify.app/games/streetsofrage/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/streetsofrage.jpg' },
    { name: 'golden axe', url: 'https://classy-figolla-4956da.netlify.app/games/goldenaxe/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/goldenaxe.jpg' },
    { name: 'kirby amazing mirror', url: 'https://classy-figolla-4956da.netlify.app/games/kirbyamazingmirror/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/kirbyamazingmirror.jpg' },
    { name: 'champion island', url: 'https://classy-figolla-4956da.netlify.app/games/championisland/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/championisland.jpg' },
    { name: 'super mario construct', url: 'https://classy-figolla-4956da.netlify.app/games/supermarioconstruct/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermarioconstruct.jpg' },
    { name: 'clicker heroes', url: 'https://classy-figolla-4956da.netlify.app/games/clickerheroes/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/clickerheroes.jpg' },
    { name: 'stair race 3d', url: 'https://classy-figolla-4956da.netlify.app/games/stairrace3d/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stairrace3d.jpg' },
    { name: 'slope 2', url: 'https://classy-figolla-4956da.netlify.app/games/slope2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/slope2.jpg' },
    { name: 'paper io 3d', url: 'https://classy-figolla-4956da.netlify.app/games/paperio3d/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/paperio3d.jpg' },
    { name: 'motox3m spooky', url: 'https://classy-figolla-4956da.netlify.app/games/motox3mspooky/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/motox3mspooky.jpg' },
    { name: 'motox3m winter', url: 'https://classy-figolla-4956da.netlify.app/games/motox3mwinter/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/motox3mwinter.jpg' },
    { name: 'snake', url: 'https://classy-figolla-4956da.netlify.app/games/snake/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/snake.jpg' },
    { name: "papa's tacomia", url: 'https://classy-figolla-4956da.netlify.app/games/papastacomia/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papastacomia.jpg' },
    { name: 'ovo', url: 'https://classy-figolla-4956da.netlify.app/games/ovo/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ovo.jpg' },
    { name: 'knife hit', url: 'https://classy-figolla-4956da.netlify.app/games/knifehit/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/knifehit.jpg' },
    { name: 'cubefield', url: 'https://classy-figolla-4956da.netlify.app/games/cubefield/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cubefield.jpg' },
    { name: 'burger and frights', url: 'https://classy-figolla-4956da.netlify.app/games/burgerandfrights/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/burgerandfrights.jpg' },
    { name: 'chess', url: 'https://classy-figolla-4956da.netlify.app/games/chess/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/chess.jpg' },
    { name: 'fnf mid fight masses', url: 'https://classy-figolla-4956da.netlify.app/games/fnfmidfight/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/midfightmasses.jpg' },
    { name: 'thumb fighter', url: 'https://classy-figolla-4956da.netlify.app/games/thumbfighter/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/thumbfighter.jpg' },
    { name: 'snow battle io', url: 'https://classy-figolla-4956da.netlify.app/games/snowbattleio/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/snowbattleio.jpg' },
    { name: 'lazy jump 3d', url: 'https://classy-figolla-4956da.netlify.app/games/lazyjump3d/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/lazyjump3d.jpg' },
    { name: 'go ball', url: 'https://classy-figolla-4956da.netlify.app/games/goball/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/goball.jpg' },
    { name: 'flippy fish', url: 'https://classy-figolla-4956da.netlify.app/games/flippyfish/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/flippyfish.jpg' },
    { name: 'shop empire', url: 'https://classy-figolla-4956da.netlify.app/games/shopempire/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shopempire.jpg' },
    { name: 'monster brawl', url: 'https://classy-figolla-4956da.netlify.app/games/monsterbrawl/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/monsterbrawl.jpg' },
    { name: 'multitask', url: 'https://classy-figolla-4956da.netlify.app/games/multitask/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/multitask.jpg' },
    { name: 'shift', url: 'https://classy-figolla-4956da.netlify.app/games/shift/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shift.jpg' },
    { name: 'shift 2', url: 'https://classy-figolla-4956da.netlify.app/games/shift2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shift2.jpg' },
    { name: 'shift 3', url: 'https://classy-figolla-4956da.netlify.app/games/shift3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shift3.jpg' },
    { name: 'shift 4', url: 'https://classy-figolla-4956da.netlify.app/games/shift4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shift4.jpg' },
    { name: 'monopoly', url: 'https://classy-figolla-4956da.netlify.app/games/monopoly/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/monopoly.jpg' },
    { name: 'picross ds', url: 'https://classy-figolla-4956da.netlify.app/games/picrossds/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/picrossds.jpg' },
    { name: 'warioware diy', url: 'https://classy-figolla-4956da.netlify.app/games/wariowarediy/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/wariowarediy.jpg' },
    { name: 'pizza tower', url: 'https://classy-figolla-4956da.netlify.app/games/pizzatower/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pizzatower.jpg' },
    { name: 'territorial io', url: 'https://classy-figolla-4956da.netlify.app/games/territorialio/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/territorialio.jpg' },
    { name: '1v1lol', url: 'https://classy-figolla-4956da.netlify.app/games/1v1lol/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/1v1lol.jpg' },
    { name: 'ballistic chickens', url: 'https://classy-figolla-4956da.netlify.app/games/ballisticchickens/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ballisticchickens.jpg' },
    { name: 'basketbros io', url: 'https://classy-figolla-4956da.netlify.app/games/basketbrosio/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/basketbrosio.jpg' },
    { name: 'minecraft classic', url: 'https://classy-figolla-4956da.netlify.app/games/mcclassic/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mcclassic.jpg' },
    { name: 'death run 3d', url: 'https://classy-figolla-4956da.netlify.app/games/deathrun3d/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/deathrun3d.jpg' },
    { name: 'soccer random', url: 'https://classy-figolla-4956da.netlify.app/games/soccerrandom/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/soccerrandom.jpg' },
    { name: 'sprinter', url: 'https://classy-figolla-4956da.netlify.app/games/sprinter/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sprinter.jpg' },
    { name: 'tron', url: 'https://classy-figolla-4956da.netlify.app/games/tron/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/tron.jpg' },
    { name: '1 on 1 soccer', url: 'https://classy-figolla-4956da.netlify.app/games/1on1soccer/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/1on1soccer.jpg' },
    { name: 'bad time simulator', url: 'https://classy-figolla-4956da.netlify.app/games/badtimesimulator/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/badtimesimulator.jpg' },
    { name: 'amazing rope police', url: 'https://classy-figolla-4956da.netlify.app/games/amazingropepolice/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/amazingropepolice.jpg' },
    { name: 'celeste', url: 'https://classy-figolla-4956da.netlify.app/games/celeste/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/celeste.jpg' },
    { name: 'just fall lol', url: 'https://classy-figolla-4956da.netlify.app/games/justfalllol/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/justfalllol.jpg' },
    { name: 'ngon', url: 'https://classy-figolla-4956da.netlify.app/games/ngon/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ngon.jpg' },
    { name: 'rocket soccer', url: 'https://classy-figolla-4956da.netlify.app/games/rocketsoccer/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/rocketsoccer.jpg' },
    { name: 'stickman climb', url: 'https://classy-figolla-4956da.netlify.app/games/stickmanclimb/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stickmanclimb.jpg' },
    { name: 'osu!mania', url: 'https://classy-figolla-4956da.netlify.app/games/osumania/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/osumania.jpg' },
    { name: 'helix jump', url: 'https://classy-figolla-4956da.netlify.app/games/helixjump/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/helixjump.jpg' },
    { name: 'dadish', url: 'https://classy-figolla-4956da.netlify.app/games/dadish/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/dadish.jpg' },
    { name: 'dadish 2', url: 'https://classy-figolla-4956da.netlify.app/games/dadish2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/dadish2.jpg' },
    { name: 'dadish 3', url: 'https://classy-figolla-4956da.netlify.app/games/dadish3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/dadish3.jpg' },
    { name: 'snow rider 3d', url: 'https://classy-figolla-4956da.netlify.app/games/snowrider3d/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/snowrider3d.jpg' },
    { name: 'tube jumpers', url: 'https://classy-figolla-4956da.netlify.app/games/tubejumpers/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/tubejumpers.jpg' },
    { name: 'yohoho io', url: 'https://classy-figolla-4956da.netlify.app/games/yohoho/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/yohoho.jpg' },
    { name: '10 minutes till dawn', url: 'https://classy-figolla-4956da.netlify.app/games/10minutestilldawn/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/10minutestilldawn.jpg' },
    { name: 'volley random', url: 'https://classy-figolla-4956da.netlify.app/games/volleyrandom/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/volleyrandom.jpg' },
    { name: 'waterworks', url: 'https://classy-figolla-4956da.netlify.app/games/waterworks/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/waterworks.jpg' },
    { name: 'geometry rash', url: 'https://classy-figolla-4956da.netlify.app/games/geometryrash/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/geometryrash.jpg' },
    { name: 'hole io', url: 'https://classy-figolla-4956da.netlify.app/games/holeio/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/holeio.jpg' },
    { name: 'sandtrix', url: 'https://classy-figolla-4956da.netlify.app/games/sandtrix/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sandtrix.jpg' },
    { name: 'shapeshipper', url: 'https://classy-figolla-4956da.netlify.app/games/shapeshipper/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shapeshipper.jpg' },
    { name: 'slope ball', url: 'https://classy-figolla-4956da.netlify.app/games/slopeball/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/slopeball.jpg' },
    { name: 'stickman golf', url: 'https://classy-figolla-4956da.netlify.app/games/stickmangolf/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stickmangolf.jpg' },
    { name: 'totally accurate battle sim', url: 'https://classy-figolla-4956da.netlify.app/games/tabs/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/totallyaccuratebattlesim.jpg' },
    { name: 'watermelon game', url: 'https://classy-figolla-4956da.netlify.app/games/watermelongame/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/watermelongame.jpg' },
    { name: 'wall smash', url: 'https://classy-figolla-4956da.netlify.app/games/wallsmash/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/wallsmash.jpg' },
    { name: 'crimson fantasia', url: 'https://classy-figolla-4956da.netlify.app/games/crimsonfantasia/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/crimsonfantasia.jpg' },
    { name: 'cut the rope', url: 'https://classy-figolla-4956da.netlify.app/games/cuttherope/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cuttherope.jpg' },
    { name: 'funny mad racing', url: 'https://classy-figolla-4956da.netlify.app/games/funnymadracing/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/funnymadracing.jpg' },
    { name: 'geometry dash lite', url: 'https://classy-figolla-4956da.netlify.app/games/gdlite/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/geometrydashlite.jpg' },
    { name: 'grand theft grotto', url: 'https://classy-figolla-4956da.netlify.app/games/grandtheftgrotto/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/grandtheftgrotto.jpg' },
    { name: 'drift mania', url: 'https://classy-figolla-4956da.netlify.app/games/driftmania/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/driftmania.jpg' },
    { name: 'rise higher', url: 'https://classy-figolla-4956da.netlify.app/games/risehigher/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/risehigher.jpg' },
    { name: 'burrito bison', url: 'https://classy-figolla-4956da.netlify.app/games/burritobison/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/burritobison.jpg' },
    { name: 'pool', url: 'https://classy-figolla-4956da.netlify.app/games/pool/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pool.jpg' },
    { name: 'redball', url: 'https://classy-figolla-4956da.netlify.app/games/redball1/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/redball.jpg' },
    { name: 'redball 3', url: 'https://classy-figolla-4956da.netlify.app/games/redball3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/redball3.jpg' },
    { name: 'redball 4', url: 'https://classy-figolla-4956da.netlify.app/games/redball4/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/redball4.jpg' },
    { name: 'redball 4 vol 2', url: 'https://classy-figolla-4956da.netlify.app/games/redballv2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/redball4vol2.jpg' },
    { name: 'redball 4 vol 3', url: 'https://classy-figolla-4956da.netlify.app/games/redballv3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/redball4vol3.jpg' },
    { name: 'rough dino', url: 'https://classy-figolla-4956da.netlify.app/games/roughdino/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/roughdino.jpg' },
    { name: 'time shooter', url: 'https://classy-figolla-4956da.netlify.app/games/timeshooter1/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/timeshooter.jpg' },
    { name: 'time shooter 2', url: 'https://classy-figolla-4956da.netlify.app/games/timeshooter2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/timeshooter2.jpg' },
    { name: 'time shooter 3', url: 'https://classy-figolla-4956da.netlify.app/games/timeshooter3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/timeshooter3.jpg' },
    { name: 'battletoads', url: 'https://classy-figolla-4956da.netlify.app/games/battletoads/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/battletoads.jpg' },
    { name: 'contra', url: 'https://classy-figolla-4956da.netlify.app/games/contra/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/contra.jpg' },
    { name: 'duck tales', url: 'https://classy-figolla-4956da.netlify.app/games/ducktales/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ducktales.jpg' },
    { name: 'kid icarus', url: 'https://classy-figolla-4956da.netlify.app/games/kidicarus/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/kidicarus.jpg' },
    { name: 'mega man 2', url: 'https://classy-figolla-4956da.netlify.app/games/megaman2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/megaman2.jpg' },
    { name: 'ninja gaiden', url: 'https://classy-figolla-4956da.netlify.app/games/ninjagaiden/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ninjagaiden.jpg' },
    { name: 'punch out', url: 'https://classy-figolla-4956da.netlify.app/games/punchout/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mikestysonspunchout.jpg' },
    { name: 'chrono trigger', url: 'https://classy-figolla-4956da.netlify.app/games/chronotrigger/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/chronotrigger.jpg' },
    { name: 'contra iii', url: 'https://classy-figolla-4956da.netlify.app/games/contraiii/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/contraiii.jpg' },
    { name: 'donkey kong country 3', url: 'https://classy-figolla-4956da.netlify.app/games/donkeykongcountry3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/donkeykongcountry3.jpg' },
    { name: 'earthbound', url: 'https://classy-figolla-4956da.netlify.app/games/earthbound/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/earthbound.jpg' },
    { name: 'final fantasy iv', url: 'https://classy-figolla-4956da.netlify.app/games/finalfantasyvi/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/finalfantasyiv.jpg' },
    { name: 'f-zero', url: 'https://classy-figolla-4956da.netlify.app/games/fzero/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fzero.jpg' },
    { name: 'super metroid', url: 'https://classy-figolla-4956da.netlify.app/games/supermetroid/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermetroid.jpg' },
    { name: 'banjo tooie', url: 'https://classy-figolla-4956da.netlify.app/games/banjotooie/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/banjotooie.jpg' },
    { name: 'harvest moon 64', url: 'https://classy-figolla-4956da.netlify.app/games/harvestmoon64/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/harvestmoon64.jpg' },
    { name: 'jet force gemini', url: 'https://classy-figolla-4956da.netlify.app/games/jetforcegemini/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/jetforcegemini.jpg' },
    { name: 'mystical ninja', url: 'https://classy-figolla-4956da.netlify.app/games/mysticalninja/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mysticalninja.jpg' },
    { name: 'turok dinosaur hunter', url: 'https://classy-figolla-4956da.netlify.app/games/turokdinosaurhunter/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/turokdinosaurhunter.jpg' },
    { name: "yoshi's story", url: 'https://classy-figolla-4956da.netlify.app/games/yoshisstory/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/yoshisstory.jpg' },
    { name: "kirby's dreamland 2", url: 'https://classy-figolla-4956da.netlify.app/games/kirbysdreamland2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/kirbysdreamland2.jpg' },
    { name: "link's awakening dx", url: 'https://classy-figolla-4956da.netlify.app/games/linksawakeningdx/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/linksawakeningdx.jpg' },
    { name: 'metroid ii', url: 'https://classy-figolla-4956da.netlify.app/games/metroidii/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/metroidii.jpg' },
    { name: 'super mario land 2', url: 'https://classy-figolla-4956da.netlify.app/games/supermarioland2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supermarioland2.jpg' },
    { name: 'wario land ii', url: 'https://classy-figolla-4956da.netlify.app/games/wariolandii/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/wariolandii.jpg' },
    { name: 'castlevania aria of sorrow', url: 'https://classy-figolla-4956da.netlify.app/games/castlevaniaariaofsorrow/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/castlevaniaariaofsorrow.jpg' },
    { name: 'final fantasy tactics adv', url: 'https://classy-figolla-4956da.netlify.app/games/finalfantasytacticsadvance/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/finalfantasytacticsadventure.jpg' },
    { name: 'drill dozer', url: 'https://classy-figolla-4956da.netlify.app/games/drilldozer/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/drilldozer.jpg' },
    { name: 'advance wars days of ruin', url: 'https://classy-figolla-4956da.netlify.app/games/advancewarsdayofruin/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/advancewarsdaysofruin.jpg' },
    { name: 'castlevania dawn of sorrow', url: 'https://classy-figolla-4956da.netlify.app/games/castlevaniadawnofsorrow/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/castlevaniadawnofsorrow.jpg' },
    { name: 'order of ecclesia', url: 'https://classy-figolla-4956da.netlify.app/games/castlevaniaorderofecclesia/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/castlevaniaorderofecclesia.jpg' },
    { name: 'partners in time', url: 'https://classy-figolla-4956da.netlify.app/games/marioandluigipartnersintime/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/marioandluigipartnersintime.jpg' },
    { name: 'comix zone', url: 'https://classy-figolla-4956da.netlify.app/games/comixzone/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/comixzone.jpg' },
    { name: 'ecco the dolphin', url: 'https://classy-figolla-4956da.netlify.app/games/eccothedolphin/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/eccothedolphin.jpg' },
    { name: 'gunstar heroes', url: 'https://classy-figolla-4956da.netlify.app/games/gunstarheroes/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/gunstarheroes.jpg' },
    { name: 'phantasy star iv', url: 'https://classy-figolla-4956da.netlify.app/games/phantasystariv/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/phantasystariv.jpg' },
    { name: 'ranger x', url: 'https://classy-figolla-4956da.netlify.app/games/rangerx/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/rangerx.jpg' },
    { name: 'ristar', url: 'https://classy-figolla-4956da.netlify.app/games/ristar/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ristar.jpg' },
    { name: 'shining force', url: 'https://classy-figolla-4956da.netlify.app/games/shiningforce/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shiningforce.jpg' },
    { name: 'shinobi iii', url: 'https://classy-figolla-4956da.netlify.app/games/shinobiiii/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shinobiiii.jpg' },
    { name: 'sonic the hedgehog', url: 'https://classy-figolla-4956da.netlify.app/games/sonicthehedgehog/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sonicthehedgehog.jpg' },
    { name: 'sonic the hedgehog 2', url: 'https://classy-figolla-4956da.netlify.app/games/sonicthehedgehog2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sonicthehedgehog2.jpg' },
    { name: 'streets of rage 2', url: 'https://classy-figolla-4956da.netlify.app/games/streetsofrage2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/streetsofrage2.jpg' },
    { name: 'vectorman', url: 'https://classy-figolla-4956da.netlify.app/games/vectorman/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/vectorman.jpg' },
    { name: 'vectorman 2', url: 'https://classy-figolla-4956da.netlify.app/games/vectorman2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/vectorman2.jpg' },
    { name: 'illusion of gaia', url: 'https://classy-figolla-4956da.netlify.app/games/illusionofgaia/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/illusionofgaia.jpg' },
    { name: 'pokemon yellow', url: 'https://classy-figolla-4956da.netlify.app/games/pokemonyellow/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pokemonyellow.jpg' },
    { name: 'abuda the alien', url: 'https://classy-figolla-4956da.netlify.app/games/abudathealien/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/abudathealien.jpg' },
    { name: 'battle beavers', url: 'https://classy-figolla-4956da.netlify.app/games/battlebeavers/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/battlebeavers.jpg' },
    { name: 'control craft 2', url: 'https://classy-figolla-4956da.netlify.app/games/controlcraft2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/controlcraft2.jpg' },
    { name: 'age of war', url: 'https://classy-figolla-4956da.netlify.app/games/ageofwar/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ageofwar.jpg' },
    { name: 'age of war 2', url: 'https://classy-figolla-4956da.netlify.app/games/ageofwar2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ageofwar2.jpg' },
    { name: 'amorphous', url: 'https://classy-figolla-4956da.netlify.app/games/amorphous/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/amorphous.jpg' },
    { name: 'bubble spinner', url: 'https://classy-figolla-4956da.netlify.app/games/bubblespinner/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bubblespinner.jpg' },
    { name: 'crush the castle', url: 'https://classy-figolla-4956da.netlify.app/games/crushthecastle/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/crushthecastle.jpg' },
    { name: 'crush the castle 2', url: 'https://classy-figolla-4956da.netlify.app/games/crushthecastle2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/crushthecastle2.jpg' },
    { name: 'epic battle fantasy', url: 'https://classy-figolla-4956da.netlify.app/games/epicbattlefantasy/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/epicbattlefantasy.jpg' },
    { name: 'epic battle fantasy 2', url: 'https://classy-figolla-4956da.netlify.app/games/epicbattlefantasy2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/epicbattlefantasy2.jpg' },
    { name: 'epic battle fantasy 3', url: 'https://classy-figolla-4956da.netlify.app/games/epicbattlefantasy3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/epicbattlefantasy3.jpg' },
    { name: 'fancy pants adventure 3', url: 'https://classy-figolla-4956da.netlify.app/games/fancypantsadventure3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/fancypantsadventure3.jpg' },
    { name: 'flood runner 2', url: 'https://classy-figolla-4956da.netlify.app/games/floodrunner2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/floodrunner2.jpg' },
    { name: 'flood runner 3', url: 'https://classy-figolla-4956da.netlify.app/games/floodrunner3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/floodrunner3.jpg' },
    { name: 'dragon boy 2', url: 'https://classy-figolla-4956da.netlify.app/games/dragonboy2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/dragonboy2.jpg' },
    { name: 'neon rider', url: 'https://classy-figolla-4956da.netlify.app/games/neonrider/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/neonrider.jpg' },
    { name: 'pandemic 2', url: 'https://classy-figolla-4956da.netlify.app/games/pandemic2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pandemic2.jpg' },
    { name: 'stick war', url: 'https://classy-figolla-4956da.netlify.app/games/stickwar/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stickwar.jpg' },
    { name: 'stick war 2', url: 'https://classy-figolla-4956da.netlify.app/games/stickwar2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stickwar2.jpg' },
    { name: 'ultimate flash sonic', url: 'https://classy-figolla-4956da.netlify.app/games/ultimateflashsonic/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ultimateflashsonic.jpg' },
    { name: 'zombocalypse', url: 'https://classy-figolla-4956da.netlify.app/games/zombocalypse/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/zombocalpyse.jpg' },
    { name: 'zombotron', url: 'https://classy-figolla-4956da.netlify.app/games/zombotron/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/zombotron.jpg' },
    { name: 'zombotron 2', url: 'https://classy-figolla-4956da.netlify.app/games/zombotron2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/zombotron2.jpg' },
    { name: 'backrooms 2d', url: 'https://classy-figolla-4956da.netlify.app/games/backrooms2d/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/backrooms2d.jpg' },
    { name: 'basket random', url: 'https://classy-figolla-4956da.netlify.app/games/basketrandom/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/basketrandom.jpg' },
    { name: 'csgo clicker', url: 'https://classy-figolla-4956da.netlify.app/games/csgoclicker/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/csgoclicker.jpg' },
    { name: 'doom', url: 'https://classy-figolla-4956da.netlify.app/games/doom/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/doom.jpg' },
    { name: 'funny shooter 2', url: 'https://classy-figolla-4956da.netlify.app/games/funnyshooter2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/funnyshooter2.jpg' },
    { name: 'gun fest', url: 'https://classy-figolla-4956da.netlify.app/games/gunfest/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/gunfest.jpg' },
    { name: 'infinite craft', url: 'https://classy-figolla-4956da.netlify.app/games/infinitecraft/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/infinitecraft.jpg' },
    { name: 'lows adventures 2', url: 'https://classy-figolla-4956da.netlify.app/games/lowsadventures2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/lowsadventures2.jpg' },
    { name: 'pako highway', url: 'https://classy-figolla-4956da.netlify.app/games/pakohighway/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pakohighway.jpg' },
    { name: 'recoil', url: 'https://classy-figolla-4956da.netlify.app/games/recoil/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/recoil.jpg' },
    { name: 'run 3 plus', url: 'https://classy-figolla-4956da.netlify.app/games/run3plus/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/run3plus.jpg' },
    { name: 'slope city', url: 'https://classy-figolla-4956da.netlify.app/games/slopecity/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/slopecity.jpg' },
    { name: 'state io', url: 'https://classy-figolla-4956da.netlify.app/games/stateio/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/stateio.jpg' },
    { name: 'sudoku', url: 'https://classy-figolla-4956da.netlify.app/games/sudoku/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/sudoku.jpg' },
    { name: 'superhero drop', url: 'https://classy-figolla-4956da.netlify.app/games/superherodrop/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/superherodrop.jpg' },
    { name: 'balloon run', url: 'https://classy-figolla-4956da.netlify.app/games/balloonrun/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/balloonrun.jpg' },
    { name: 'crazy tunnel 3d', url: 'https://classy-figolla-4956da.netlify.app/games/crazytunnel3d/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/crazytunnel3d.jpg' },
    { name: 'minecraft [v1.8]', url: 'https://classy-figolla-4956da.netlify.app/games/eagler1.8/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mc1.8.jpg' },
    { name: 'geometry dash sky', url: 'https://classy-figolla-4956da.netlify.app/games/geometrydashsky/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/geometrydashsky.jpg' },
    { name: 'wubzzys adventure', url: 'https://classy-figolla-4956da.netlify.app/games/wubzzysamazingadventure/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/wubzzysamazingadventure.jpg' },
    { name: 'gold digger frvr', url: 'https://classy-figolla-4956da.netlify.app/games/golddiggerfrvr/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/golddiggerfrvr.jpg' },
    { name: 'hexgl', url: 'https://classy-figolla-4956da.netlify.app/games/hexgl/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/hexgl.jpg' },
    { name: 'house of hazards', url: 'https://classy-figolla-4956da.netlify.app/games/houseofhazards/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/houseofhazards.jpg' },
    { name: 'pick crafter', url: 'https://classy-figolla-4956da.netlify.app/games/pickcrafter/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/pickcrafter.jpg' },
    { name: 'precision client', url: 'https://classy-figolla-4956da.netlify.app/games/precisionclient/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/precisionclient.jpg' },
    { name: 'subway runner', url: 'https://classy-figolla-4956da.netlify.app/games/subwayrunner/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/subwayrunner.jpg' },
    { name: 'xx142-b2.exe', url: 'https://classy-figolla-4956da.netlify.app/games/xx142-b2.exe/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/xx142b2.exe.jpg' },
    { name: 'canopy', url: 'https://classy-figolla-4956da.netlify.app/games/canopy/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/canopy.jpg' },
    { name: 'cave chaos', url: 'https://classy-figolla-4956da.netlify.app/games/cavechaos/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cavechaos.jpg' },
    { name: 'change type', url: 'https://classy-figolla-4956da.netlify.app/games/changetype/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/changetype.jpg' },
    { name: 'cheese dreams', url: 'https://classy-figolla-4956da.netlify.app/games/cheesedreams/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cheesedreams.jpg' },
    { name: 'chisel', url: 'https://classy-figolla-4956da.netlify.app/games/chisel/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/chisel.jpg' },
    { name: 'chisel 2', url: 'https://classy-figolla-4956da.netlify.app/games/chisel2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/chisel2.jpg' },
    { name: 'ditto', url: 'https://classy-figolla-4956da.netlify.app/games/ditto/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/ditto.jpg' },
    { name: 'feed me', url: 'https://classy-figolla-4956da.netlify.app/games/feedme/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/feedme.jpg' },
    { name: 'final ninja', url: 'https://classy-figolla-4956da.netlify.app/games/finalninja/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/finalninja.jpg' },
    { name: 'frost bite', url: 'https://classy-figolla-4956da.netlify.app/games/frostbite/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/frostbite.jpg' },
    { name: 'frost bite 2', url: 'https://classy-figolla-4956da.netlify.app/games/frostbite2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/frostbite2.jpg' },
    { name: 'icebreaker', url: 'https://classy-figolla-4956da.netlify.app/games/icebreaker/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/icebreaker.jpg' },
    { name: 'mutiny', url: 'https://classy-figolla-4956da.netlify.app/games/mutiny/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/mutiny.jpg' },
    { name: 'nitrome must die', url: 'https://classy-figolla-4956da.netlify.app/games/nitromemustdie/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/nitromemustdie.jpg' },
    { name: 'oodlegobs', url: 'https://classy-figolla-4956da.netlify.app/games/oodlegobs/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/oodlegobs.jpg' },
    { name: 'super treadmill', url: 'https://classy-figolla-4956da.netlify.app/games/supertreadmill/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/supertreadmill.jpg' },
    { name: 'swindler', url: 'https://classy-figolla-4956da.netlify.app/games/swindler/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/swindler.jpg' },
    { name: 'test subject arena', url: 'https://classy-figolla-4956da.netlify.app/games/testsubjectarena/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/testsubjectarena.jpg' },
    { name: 'test subject complete', url: 'https://classy-figolla-4956da.netlify.app/games/testsubjectcomplete/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/testsubjectcomplete.jpg' },
    { name: 'twin shot', url: 'https://classy-figolla-4956da.netlify.app/games/twinshot/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/twinshot.jpg' },
    { name: 'twin shot 2', url: 'https://classy-figolla-4956da.netlify.app/games/twinshot2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/twinshot2.jpg' },
    { name: 'three line', url: 'https://classy-figolla-4956da.netlify.app/games/3line/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/threeline.jpg' },
    { name: 'bike champ', url: 'https://classy-figolla-4956da.netlify.app/games/bikechamp/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bikechamp.jpg' },
    { name: 'bike champ 2', url: 'https://classy-figolla-4956da.netlify.app/games/bikechamp2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/bikechamp2.jpg' },
    { name: 'corporation inc', url: 'https://classy-figolla-4956da.netlify.app/games/corporationinc/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/corporationinc.jpg' },
    { name: 'shop empire fable', url: 'https://classy-figolla-4956da.netlify.app/games/shopempirefable/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/shopempirefable.jpg' },
    { name: 'cactus mccoy', url: 'https://classy-figolla-4956da.netlify.app/games/cactusmccoy/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cactusmccoy.jpg' },
    { name: 'cactus mccoy 2', url: 'https://classy-figolla-4956da.netlify.app/games/cactusmccoy2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/cactusmccoy2.jpg' },
    { name: 'papa louie', url: 'https://classy-figolla-4956da.netlify.app/games/papalouie/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papalouie.jpg' },
    { name: 'papa louie 2', url: 'https://classy-figolla-4956da.netlify.app/games/papalouie2/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papalouie2.jpg' },
    { name: 'papa louie 3', url: 'https://classy-figolla-4956da.netlify.app/games/papalouie3/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/papalouie3.jpg' },
    { name: 'steak and jake', url: 'https://classy-figolla-4956da.netlify.app/games/steakandjake/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/steakandjake.jpg' },
    { name: 'steak and jake midnight', url: 'https://classy-figolla-4956da.netlify.app/games/steakandjakemidnightmarch/', imageUrl: 'https://classy-figolla-4956da.netlify.app/images/thumbnails/steakandjakemidnightmarch.jpg' },
];